### ISSUE TITLE
Make public speaker profile page more nuanced

### ISSUE THREAD

**Issue by mattstauffer** [tighten/symposium#224]
E.g. searching for "FL" picks me up, but not "florida."
E.g. the page layout is a little janky/crammed/unclear/inconsistent:

![image](https://user-images.githubusercontent.com/151829/27355077-ae3675f8-55d7-11e7-9b2e-a48a27163a65.png)
![image](https://user-images.githubusercontent.com/151829/27355098-bdff4636-55d7-11e7-85c0-7c013ae7cc06.png)
![image](https://user-images.githubusercontent.com/151829/27355107-c2ac02f0-55d7-11e7-896d-b5174c73caa0.png)

It's also not clear that you can search by location, so we should make that obvious through UI or words.

It also might be nice to be able to add "within ___ miles/km of ___"

**Comment by jwheat** [comment]
I decided to play around with this issue starting with the UI.  I noticed you're not using bootstrap classes in your views, are you opposed to me introducing these or would you prefer to keep it "clean" since they're not used in other places in the app?  If you'd prefer I can create some new classes in app.css instead to get a multi column list of speakers.

**Comment by mattstauffer** [comment]
I can't honestly remember, but if you're noticing that we're not using them elsewhere it's probably good to keep it that way. :)

**Comment by andrewmile** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make public speaker profile page more nuanced](https://trello.com/c/V0etQocK/110-make-public-speaker-profile-page-more-nuanced)
